Updated clip/{pc,pp} cargo.stuff dot_commands.stuf, added vi-stub, removed duplicate send2

diff --git a/clip/pc b/clip/pc
--- a/clip/pc
+++ b/clip/pc
@@ -7,5 +7,5 @@ elif [ -d "/Applications" ]; then # macos
 elif [ -d "/cygdrive/c/cygwin64" ]; then # cygwin
   cat "$@" > /dev/clipboard
 else
-  echo "Cannot copy as not gui" > /dev/stderr
+  echo "Cannot copy as not gui" 1>&2 
 fi
diff --git a/clip/pp b/clip/pp
--- a/clip/pp
+++ b/clip/pp
@@ -6,7 +6,7 @@ elif [ -d "/Applications" ]; then # macos
 elif [ -d "/cygdrive/c/cygwin64" ]; then # cygwin
   paste() { cat /dev/clipboard; }
 else
-  echo "Cannot paste as not gui" > /dev/stderr
+  echo "Cannot paste as not gui" 1>&2 
 fi
 if [ -n "$1" ]; then
   paste | tee "$1"
